### ISSUE TITLE
Data Science and matplotlib implementation

### ISSUE THREAD

**Issue by GeneralSubhra** [dsc-tiu/open-source-ml-ai#10]
I have made some some data science project and also the basic implementation of matplotlib which will help beginners to understand ML better . I have made a Bollywood dataset project which is basically analysing dataset and a titanic dataset which is a classification problem.

**Comment by diffrxction** [comment]
> I have made some some data science project and also the basic implementation of matplotlib which will help beginners to understand ML better . I have made a Bollywood dataset project which is basically analysing dataset and a titanic dataset which is a classification problem.

Cool, @GeneralSubhra ! I am assigning you the task.
