### ISSUE TITLE
Natural Language Processing Task

### ISSUE THREAD

**Issue by ArmaanSeth** [dsc-tiu/open-source-ml-ai#19]
Here I will implement NLP algorithm from scratch.  Along with this I'll provide a detailed documentation comprising of the intuition behind natural language processing and about terms like lemmatizing and stemming ,etc.

@diffrxction  please add the hacktoberfest and other desired labels to this issue.

Regards
Armaan Seth

**Comment by diffrxction** [comment]
Sounds perfect! Go ahead @ArmaanSeth.
