### ISSUE TITLE
Titanic Dataset

### ISSUE THREAD

**Issue by Padi-Rishitha** [dsc-tiu/open-source-ml-ai#21]
@DSCTIU can I work on this dataset

**Comment by Padi-Rishitha** [comment]
@DSCTIU please can you asssign this work to me

**Comment by diffrxction** [comment]
> @DSCTIU can I work on this dataset

Hello, @Padi-Rishitha we already have had a submission for titanic dataset in #11 so your addition would be redundant. Instead, if you are comfortable with Matplotlib and can showcase some basic to intermediate graphs, code and documentation for the same, then that would be great. 

If you choose to go with this, please let me know, I will assign the relevant issue to you and you can create a new folder titled `Matplotlib Implementation` and include your code and documentation there itself. Thank you.

**Comment by diffrxction** [comment]
> @diffrxction Please can you say what happen? Actually I am new to Open Source. So, please let me know!!

Hey, I have mentioned the suggestions and approved + merged your pull request after some minor fixes. If you have any doubts then leave a comment under your pull request itself. I will answer them there.

**Comment by Padi-Rishitha** [comment]
Thanks!!
