### ISSUE TITLE
Image Processing Tasks

### ISSUE THREAD

**Issue by diffrxction** [dsc-tiu/open-source-ml-ai#3]
Requirments:
Code and description in Markdown files

- Reading images in Python
- Writing images in Python
- Mean Filter implementation
- Median Filter implementation
- Displaying images in plots and subplots using matplotlib
- Plotting datasets as graphs and charts using matplotlib and seaborn.

If you have any other implementations you would like to contribute, then mention them in the comments and I will allocate them to you.

Folder structure to follow:

```
├── Image Processing
│   ├── Image Reading, Writing (Create sub-folder here)
│   │   ├──ReadingImagesopencv.py  
│   │   ├──ReadingImagesopencv.md  
│   │   ├──WritingImagesopencv.py  
│   │   ├──WritingImagesopencv.md  
│   ├── Matplotlib Operations(Create sub-folder here)
│   │   ├──PlottingData.py  
│   │   ├──PlottingData.md  
│   │   ├──Subplots.py  
│   │   ├──Subplots.md  (and so on....)
```

Please see, you will be allotted a small portion of the topics mentioned above just so all interested people have a chance to contribute.

Also notice the labels for each issue, that will give you an idea about what kind of work you are expected to do.

Cheers! 😄

**Comment by AAnirudh07** [comment]
Hi,
I'd like to work on the python script for reading images (with options). Additionally, I thought of adding a script for reading video streams. Could you please assign this task to me?

**Comment by diffrxction** [comment]
Hey @AAnirudh07, sounds great, if possible please include code for reading images faster than the inbuilt image reader (this is not absolutely necessary but could be a good add-on to this repo). Reason being that the default video readers read at comparatively lower fps than the video default fps reading.

For just reading images and videos, try to also include ways to write them in their relevant libraries, in different color channels and ranges. And lastly please provide a documentation file to go along with your code in Markdown format (.md). Thank you and all the best!

**Comment by AAnirudh07** [comment]
Can I make a PR on how to write images and videos in Python (code + documentation)?

**Comment by diffrxction** [comment]
> Can I make a PR on how to write images and videos in Python (code + documentation)?

Yeah no problem buddy. Go ahead, make a separate sub-folder like you did last time and include both code and documentation for the same.
